name: Run Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-11.0

    name: Run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup .NET Core 5.0 @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Setup .NET Core 3.1 @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Create build
        run: dotnet build "src/IntrinsicsGeneric" -c Release --force

      - name: Run Unit Tests
        run: dotnet test "src/IntrinsicsGeneric.UnitTests" -c Release
